services:

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=Docker
    volumes:
      - /home/epilif3sotnas/coisas/projects/docker-db/learn-docker/postgresql:/var/lib/postgresql/data

  learn-docker:
    image: learn-docker
    restart: always
    ports:
      - 5000:5000

volumes:
  db:
    driver: local